// Generated by CoffeeScript 1.6.3
(function() {
  var inspect, myTest, utils;

  utils = require("./utils");

  inspect = utils.inspect;

  myTest = function() {
    return console.log(inspect("Hello world number 2"));
  };

  myTest();

}).call(this);
